config/routes.rb
StorySystem::Application.routes.draw do

  resources :webextras

  resources :airdates

  resources :shoots

  get "staffs/login"
  get "staffs/logout"
  get "staffs/forgot"
  get "home/index"
  get "characters/tag_list"
  get "stories/clone"
  get "stories/tag_list"
  get "staffs/contact_us"
  get "staffs/contact_staff"
  get "home/sign_in_google"
  get "home/complete_sign_in_google"
  resources :staffs
  resources :stories
  resources :characters
  resources :shoots do
  get :autocomplete_story_name, :on => :collection
end

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/staff.rb
require 'mini_magick'
class Staff < ActiveRecord::Base
  validates :userid ,:email ,:first_name ,:last_name ,:title ,:phone ,:presence => true
  validates_uniqueness_of :email
  validates_uniqueness_of :userid
  validates_length_of :userid, :minimum => 5
  validates_length_of :password, :within => 5..50
  validates_confirmation_of :password
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "must be valid"
  before_save :hash_password
  has_many :shoots ,:dependent => :destroy
  has_many :stories ,:dependent => :destroy
  has_many :stories , :dependent => :destroy
  has_many :webextra , :dependent => :destroy
  def hash_password
    if password_changed?
      self.password = Digest::SHA1.hexdigest(password)
    end
  end
  def save_avatar(fileio)
    # ENSURE WE HAVE A FILE AND IT IS THE CORRECT CONTENT TYPE
    if (fileio && fileio.content_type =~ /^image/) then


      extension = File.extname(fileio.original_filename)


      file_name = self.id.to_s + '_' + Time.now.to_i.to_s
            AWS::S3::S3Object.store(sanitize_filename(file_name + extension), fileio.read, BUCKET, :access => :public_read)

  
      # PERFORM THE MINIMAGICK CHANGES

      begin
        mm = MiniMagick::Image.open(AWS::S3::S3Object.url_for(file_name + extension, BUCKET, :authenticated => false), File.extname(AWS::S3::S3Object.url_for(file_name + extension, BUCKET, :authenticated => false)))

        mm.resize("60X60")
        mm.write(AWS::S3::S3Object.url_for(file_name + extension, BUCKET, :authenticated => false))
      rescue
      end
      # UPDATE ATTRIBUTES
      self.avatar = AWS::S3::S3Object.url_for(file_name + extension, BUCKET, :authenticated => false)
      self.update_attribute("avatar", AWS::S3::S3Object.url_for(file_name + extension, BUCKET, :authenticated => false))
    end
  end

  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/,'_')
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # GET /staffs
  # GET /staffs.xml
  sortable_attributes :userid ,:first_name ,:last_name ,:title ,:email ,:phone
  before_filter :staff_is_admin ,:only => [:index ,:destroy]
  def index
    query_string = ""
    conditions = {}
    if params[:staff]
      if params[:staff][:userid] != nil and params[:staff][:userid] != ''
        query_string = query_string + " AND UPPER(userid) LIKE :userid"
        conditions[:userid] = "%" + params[:staff][:userid].strip.upcase + "%"
      end
      if params[:staff][:first_name] != nil and params[:staff][:first_name] != ''
        query_string = query_string + " AND UPPER(first_name) LIKE :first_name"
        conditions[:first_name] = "%" + params[:staff][:first_name].strip.upcase + "%"
      end
      if params[:staff][:last_name] != nil and params[:staff][:last_name] != ''
        query_string = query_string + " AND UPPER(last_name) LIKE :last_name"
        conditions[:last_name] = "%" + params[:staff][:last_name].strip.upcase + "%"
      end
      if params[:staff][:email] != nil and params[:staff][:email] != ''
        query_string = query_string + " AND UPPER(email) LIKE :email"
        conditions[:email] = "%" + params[:staff][:email].strip.upcase + "%"
      end
      if params[:staff][:title] != nil and params[:staff][:title] != ''
        query_string = query_string + " AND UPPER(title) LIKE :title"
        conditions[:title] = "%" + params[:staff][:title].strip.upcase + "%"
      end
      if params[:staff][:phone] != nil and params[:staff][:phone] != ''
        query_string = query_string + " AND UPPER(phone) LIKE :phone"
        conditions[:phone] = "%" + params[:staff][:phone].strip.upcase + "%"
      end
    end
    @staffs =  Staff.where("created_at IS NOT NULL" + query_string, conditions).find(:all ,:order => sort_order).paginate :page => params[:page],:per_page => params[:staff] ? params[:staff][:record_number] : 10

    respond_to do |format|
      format.html # index.html.erb
      format.js {
        render :update do |page|
          # 'page.replace' will replace full "results" block...works for this example
          # 'page.replace_html' will replace "results" inner html...useful elsewhere
          page.replace 'results', :partial => 'search_results'
        end
      }
    end
  end

  # GET /staffs/1
  # GET /staffs/1.xml
  def show
    @staff = Staff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.xml
  def new
    @staff = Staff.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @staff }
    end
  end

  # GET /staffs/1/edit
  def edit

    @staff = Staff.find(params[:id])
    if session[:userid] != nil and session[:userid] != ''
      if session[:userid] != 'admin'

        @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])

        if @valid_staff.id != @staff.id
          flash[:notice] = "You don't have access to this section."
          redirect_to '/'
          return
        end
      end
    else
      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
      return
    end
  end

  # POST /staffs
  # POST /staffs.xml
  def create
    @staff = Staff.new(params[:staff])

    respond_to do |format|
      if @staff.save
        if params[:avatar] then
          @staff.save_avatar(params[:avatar])
        end
        format.html { redirect_to(@staff, :notice => 'Staff was successfully created.') }
        format.xml  { render :xml => @staff, :status => :created, :location => @staff }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @staff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.xml
  def update
    @staff = Staff.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
        if params[:avatar] then
          @staff.save_avatar(params[:avatar])
        end
        format.html { redirect_to(@staff, :notice => 'Staff was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @staff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.xml
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to(staffs_url) }
      format.xml  { head :ok }
    end
  end
  def authenticate

    @staff = Staff.new(params[:staff_form])
    #find records with userid,password
    valid_user = Staff.find(:first, :conditions => ["userid = ? and password = ?", @staff.userid, Digest::SHA1.hexdigest(@staff.password)])

    #if statement checks whether valid_user exists or not
    if valid_user
      #creates a session with username
      session[:userid]=valid_user.userid
      #redirects the user to our private page.
      redirect_to '/'
    else
      flash[:notice] = "Invalid User/Password"
      redirect_to :action=> 'login'
    end
  end

  def login
  end
  def logout
    if session[:userid]
      reset_session
      redirect_to '/'
    end
  end
  def forgot
  end
  def contact_us




  end
  def contact_staff

  end
  def send_contact_staff
    respond_to do |format|
      if verify_recaptcha( :message => "Oh! It's error with reCAPTCHA!")
        subject = params[:contact_staff][:subject]
        staff = Staff.find_by_id(params[:contact_staff][:id].to_i)
        if staff
          recipient = staff.email
          message =  params[:contact_staff][:message]
          UserMailer.contact_staff(recipient, subject, staff, message).deliver
          format.html { redirect_to(:controller => 'staffs', :action =>"index") }
        else
          format.html { redirect_to(:controller => 'staffs', :action =>"contact_staff", :contact_staff => { :error => "The staff doesn't exist in the system" ,:subject => params[:contact_staff][:subject] , :message => params[:contact_staff][:message], :id => params[:contact_staff][:id]})}
        end
      else
        format.html { redirect_to(:controller => 'staffs', :action =>"contact_staff", :contact_staff => { :error => "Oh! It's error with reCAPTCHA!" ,:subject => params[:contact_staff][:subject] , :message => params[:contact_staff][:message], :id => params[:contact_staff][:id]})}
      end
    end
  end
  def send_contact_us

    respond_to do |format|
      if verify_recaptcha( :message => "Oh! It's error with reCAPTCHA!")
        recipient = 'nhut2020@yahoo.com'
        subject = params[:contact_us][:subject]
        staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
        message =  params[:contact_us][:message]
        UserMailer.contact_us(recipient, subject, staff, message).deliver
        format.html { redirect_to(:controller => 'home', :action =>"index") }
      else
        format.html { redirect_to(:controller => 'staffs', :action =>"contact_us", :contact_us => { :error => "Oh! It's error with reCAPTCHA!" ,:subject => params[:contact_us][:subject] , :message => params[:contact_us][:message]})}
      end
    end
  end
  def sendmail
    recipient = params[:mailform][:email]
    subject = 'Get your password'
    staff = Staff.find(:first, :conditions => ["email = ? ", recipient])
    chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ23456789'
    password = ''
    6.times { |i| password << chars[rand(chars.length)] }

    if staff
      staff.password = password
      UserMailer.forgot(recipient, subject, staff).deliver
      staff.update_attributes(:password => password)
    else
      flash[:notice] = recipient + " doesn't exist in the system"
      redirect_to '/'
      return
    end
    return if request.xhr?
    flash[:notice] = 'Message sent successfully'
    redirect_to '/'
  end
  def staff_is_admin
    if session[:userid] == nil or session[:userid] == ''

      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
    if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid != 'admin'
      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff, :html => { :multipart => true}) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% @staff.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password ,:value => ''%>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation %>
    </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <p>
    <%= image_tag @staff.avatar ? @staff.avatar : 'logo.jpg', :size => "60x60" %>
  </p>
  <p>
    Avatar<br />
    <%= file_field_tag 'avatar' %>
  </p>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
    <div class="field">
      <%= f.label :is_senior_producer %><br />
      <%= f.check_box :is_senior_producer %>
    </div>
    <div class="field">
      <%= f.label :is_assignment_editor %><br />
      <%= f.check_box :is_assignment_editor %>
    </div>
    <div class="field">
      <%= f.label :is_producer %><br />
      <%= f.check_box :is_producer %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/_search_results.html.erb
<div id="results">
  <table>
    <tr>
      <%= sortable_table_header :name => "Userid",   :sort => "userid" ,:class => 'pagination ajax'  %>
      <%= sortable_table_header :name => "First name",   :sort => "first_name" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Last name",   :sort => "last_name" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Email",   :sort => "email" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Title",   :sort => "title" ,:class => 'pagination ajax' %>
      <th>Avatar</th>
      <%= sortable_table_header :name => "Phone",   :sort => "phone" ,:class => 'pagination ajax' %>
      <th>Is senior producer</th>
      <th>Is assignment editor</th>
      <th>Is producer</th>
      <th></th>
      <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
        <th></th>
      <% end %>
      <th></th>
      <th></th>
    </tr>

    <% @staffs.each do |staff| %>
      <tr>
        <td><%= html_escape(staff.userid) %></td>
        <td><%= html_escape(staff.first_name) %></td>
        <td><%= html_escape(staff.last_name) %></td>
        <td><%= html_escape(staff.email) %></td>
        <td><%= html_escape(staff.title) %></td>
        <td>  <%= image_tag staff ? (staff.avatar ? staff.avatar : 'logo.jpg')  : 'logo.jpg', :size => "60x60" %></td>
        <td><%= html_escape(staff.phone) %></td>
        <td><%= staff.is_senior_producer %></td>
        <td><%= staff.is_assignment_editor %></td>
        <td><%= staff.is_producer %></td>
        <td><%= link_to 'Show', staff %></td>
        <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
          <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <% end %>
        <td><%= link_to 'Destroy', staff, :confirm => 'Are you sure?', :method => :delete %></td>
        <td> <%= link_to "Contact Us",:controller => "staffs", :action => "contact_staff", :contact_staff =>{:id => staff.id  } %></td>
      </tr>
    <% end %>
  </table>
    <%= will_paginate  @staffs, :class => 'pagination ajax' %>
  </div>

app/views/staffs/contact_staff.html.erb
<% if params[:contact_staff] %>
  <% if params[:contact_staff][:error] %>
  <div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
  
    <%= params[:contact_staff][:error] %>
  </div>
<% end %>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'send_contact_staff' %>

<p>
  <b>Subject:</b> <br/>
  <%= text_field("contact_staff", "subject",:size=>"53" , :maxlength => '255', :value => params[:contact_staff] ? params[:contact_staff][:subject] : '') %>
</p>

<p>
  <b>Message:</b>
  <b</b><br/>
  <%= text_area("contact_staff" ,"message", :size => "40x10", :value => params[:contact_staff] ? params[:contact_staff][:message] : '') %>
</p>
<script type="text/javascript">

  function checkValidate() {
    if ($("contact_staff_subject").getValue() == null || $("contact_staff_subject").getValue() == '') {
      alert ("Please type in Subject");
      return false;
    }
    if ($("contact_staff_message").getValue() == null || $("contact_staff_message").getValue() == '') {
      alert ("Please type in Message");
      return false;
    }

    return true;

 
  }
</script>
<%= recaptcha_tags %>
  <%= hidden_field("contact_staff" , "id" , :value =>params[:contact_staff] ? params[:contact_staff][:id] : '')  %>
<input type="submit" value=" Send " onclick=" return checkValidate();"/>
<br/>
<%= link_to 'Back', url_for(:back) %>

app/views/staffs/contact_us.html.erb
<% if params[:contact_us] %>
  <% if params[:contact_us][:error] %>
  <div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
  
    <%= params[:contact_us][:error] %>
  </div>
<% end %>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'send_contact_us' %>

<p>
  <b>Subject:</b> <br/>
  <%= text_field("contact_us", "subject",:size=>"53" , :maxlength => '255', :value => params[:contact_us] ? params[:contact_us][:subject] : '') %>
</p>

<p>
  <b>Message:</b>
  <b</b><br/>
  <%= text_area("contact_us" ,"message", :size => "40x10", :value => params[:contact_us] ? params[:contact_us][:message] : '') %>
</p>
<script type="text/javascript">

  function checkValidate() {
    if ($("contact_us_subject").getValue() == null || $("contact_us_subject").getValue() == '') {
      alert ("Please type in Subject");
      return false;
    }
    if ($("contact_us_message").getValue() == null || $("contact_us_message").getValue() == '') {
      alert ("Please type in Message");
      return false;
    }

    return true;

 
  }
</script>
<%= recaptcha_tags %>
<input type="submit" value=" Send " onclick=" return checkValidate();"/>
<br/>
<%= link_to 'Back', url_for(:back) %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/forgot.html.erb
<%= link_to 'Home', home_index_path %>
<p/>
<% if flash[:notice] %>
<div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
<%= flash[:notice] %>
</div>
<% end %>

<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'sendmail' %>
Send Mail to get your password:
<br/>
<%= text_field("mailform", "email",:size=>"20" ) %>

<input type="submit" value=" Send " />

app/views/staffs/index.html.erb
<h1>Listing staffs</h1>
<%= form_for :staff, :remote => true, :html => { :method => :get} do |f| %>
  <table>
    <tr>
      <td>
        <%= f.label :userid %>
      </td>
      <td>
        <%= f.text_field :userid, :value => params[:staff] ? params[:staff][:userid] : '' %>
      </td>
      <td>
        <%= f.label :first_name %>
      </td>
      <td>
        <%= f.text_field :first_name, :value => params[:staff] ? params[:staff][:first_name] : '' %>
      </td>
      <td>
        <%= f.label :last_name %>
      </td>
      <td>
        <%= f.text_field :last_name, :value => params[:staff] ? params[:staff][:last_name] : '' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :email %>
      </td>
      <td>
        <%= f.text_field :email, :value => params[:staff] ? params[:staff][:email] : '' %>
      </td>
      <td>
        <%= f.label :title %>
      </td>
      <td>
        <%= f.text_field :title, :value => params[:staff] ? params[:staff][:title] : '' %>
      </td>
      <td>
        <%= f.label :phone %>
      </td>
      <td>
        <%= f.text_field :phone, :value => params[:staff] ? params[:staff][:phone] : '' %>
      </td>
    </tr>
  </table>
  <%= submit_tag("Search") %>
  <%= render "search_results" %>
  <br />
  Display <%= f.select(:record_number, [[10,10], [20, 20], [50, 50], [100, 100]] , :selected => params[:staff] ? params[:staff][:record_number] : 10) %> records


  <br/>
  <%= link_to 'New Staff', new_staff_path %>
<% end %>

app/views/staffs/login.html.erb
<p/>
<% if flash[:notice] %>
<div style="font-family:'Trebuchet MS'; color:#FF0000; font-size:14px;">
<%= flash[:notice] %>
</div>
<% end %>
<script type="text/javascript">

  function checkAdmin() {
    if ($("staff_form_userid").getValue() != 'admin') {
      alert ("You should be the admin");
      return false;
    }

    return true;


  }
</script>
<!--creates form, exectues the authenticate method when the submit button is clicked-->
<%= form_tag :action=>'authenticate' %>
User name:
<br/>
<%= text_field("staff_form", "userid",:size=>"20" ) %>
<br/>
Password:
<br/>
<%= password_field("staff_form", "password",:size=>"20" )
%>
<br/>
<%= link_to 'Forgot password' ,:controller => "staffs", :action => "forgot" %>
<br/>
<input type="submit" value=" LOGIN " onclick =" return checkAdmin();" />

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= html_escape(@staff.userid) %>
</p>

<p>
  <b>First name:</b>
  <%= html_escape(@staff.first_name) %>
</p>

<p>
  <b>Last name:</b>
  <%= html_escape(@staff.last_name) %>
</p>

<p>
  <b>Email:</b>
  <%= html_escape(@staff.email) %>
</p>

<p>
  <b>Title:</b>
  <%= html_escape(@staff.title) %>
</p>

<p>
  <b>Avatar:</b>
  <%= image_tag @staff.avatar ? @staff.avatar : 'logo.jpg', :size => "60x60" %>
</p>
z
<p>
  <b>Phone:</b>
  <%= html_escape(@staff.phone) %>
</p>

<p>
  <% if @staff.is_senior_producer == true %>
    <b>Senior Producer</b>
  <% end %>
</p>

<p>
  <% if @staff.is_assignment_editor == true %>
    <b>Assignment Editor</b>
  <% end %>
</p>

<p>
  <% if @staff.is_producer == true %>
    <b>Producer</b>
  <% end %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |

<%= link_to 'Back', url_for(:back) %>