config/routes.rb
StorySystem::Application.routes.draw do

  resources :webextras

  resources :airdates

  resources :shoots

  get "staffs/login"
  get "staffs/logout"
  get "staffs/forgot"
  get "home/index"
  get "characters/tag_list"
  get "stories/clone"
  get "stories/tag_list"
  get "staffs/contact_us"
  get "staffs/contact_staff"
  get "home/sign_in_google"
  get "home/complete_sign_in_google"
  resources :staffs
  resources :stories
  resources :characters
  resources :shoots do
  get :autocomplete_story_name, :on => :collection
end

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/shoot.rb
class Shoot < ActiveRecord::Base
  validates :name, :crew_requirements  ,:location ,:notes , :presence => true
  belongs_to :cameraperson ,:class_name => 'Staff'
  belongs_to :approver ,:class_name => 'Staff'
  belongs_to :story
  belongs_to :staff
    def Shoot.send_shoot

     conditions = {}
     conditions[:check_mail] = false
    shoots = Shoot.where("check_mail = :check_mail", conditions)
    conditions = {}
    conditions[:is_is_senior_producer] = true
    conditions[:is_assignment_editor] = true
    accessors = Staff.where("is_senior_producer = :is_is_senior_producer or is_assignment_editor = :is_assignment_editor", conditions)
    subject = 'Shoot'
    shoots.each do |shoot|
      accessors.each do |accessor|
        UserMailer.send_shoot( subject, shoot, shoot.staff, accessor.email).deliver
        shoot.update_attribute("check_mail", false)
      end
    end
  end
end

app/controllers/shoots_controller.rb
class ShootsController < ApplicationController
  # GET /shoots
  # GET /shoots.xml
  uses_tiny_mce :options => {
    :theme => 'advanced',
    :theme_advanced_resizing => true,
    :theme_advanced_buttons2 => "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    :theme_advanced_resize_horizontal => false,
    :plugins => %w{ table fullscreen }
  }
  auto_complete_for :story, :name


  before_filter :from_story_show
  sortable_attributes :date , :crew_requirements  ,:location, :name
  before_filter :permission , :only => [:edit , :destroy]
  def auto_complete_for_story_name
    @stories = Story.find(:all , :conditions => ["name like (?) and archived = ?", "%" + params[:story][:name].to_s + "%", false],:order => 'name asc')
    render :partial => 'story'
  end
  def index


    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    query_string = ""
    conditions = {}
    if params[:story]
      if params[:story][:name] != nil and params[:story][:name].strip != ''
        story = Story.find_by_name(params[:story][:name].strip)
        if story
          query_string = query_string + " AND  story_id = :story_id"
          conditions[:story_id] = story.id
        end
      end
    end
    if params[:shoot]
      if params[:shoot][:crew_requirements] != nil and params[:shoot][:crew_requirements] != ''
        query_string = query_string + " AND UPPER(crew_requirements) LIKE :crew_requirements"
        conditions[:crew_requirements] = "%" + params[:shoot][:crew_requirements].strip.upcase + "%"
      end
      if params[:shoot][:location] != nil and params[:shoot][:location] != ''
        query_string = query_string + " AND UPPER(location) LIKE :location"
        conditions[:location] = "%" + params[:shoot][:location].strip.upcase + "%"
      end
      if params[:shoot][:cameraperson_id] != nil and params[:shoot][:cameraperson_id] != ''
        query_string = query_string + " AND cameraperson_id = :cameraperson_id"
        conditions[:cameraperson_id] = params[:shoot][:cameraperson_id]
      end

      if params[:shoot][:name] != nil and params[:shoot][:name] != ''
        query_string = query_string + " AND UPPER(name) LIKE :name"
        conditions[:name] = "%" + params[:shoot][:name].strip.upcase + "%"
      end
    else
      if Story.find_by_id(session[:story_id])
        query_string = query_string + " AND story_id = :story_id"
        conditions[:story_id] = session[:story_id]
      end
    end

    @shoots = Shoot.where("created_at IS NOT NULL" + query_string, conditions).find(:all ,:order => sort_order).paginate :page => params[:page],:per_page => params[:shoot] ? params[:shoot][:record_number] : 10
    respond_to do |format|
      format.html # index.html.erb
      format.js {
        render :update do |page|
          # 'page.replace' will replace full "results" block...works for this example
          # 'page.replace_html' will replace "results" inner html...useful elsewhere
          page.replace 'results', :partial => 'search_results'
        end
      }
    end
  end

  # GET /shoots/1
  # GET /shoots/1.xml
  def show
    @shoot = Shoot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shoot }
    end
  end

  # GET /shoots/new
  # GET /shoots/new.xml
  def new
    @shoot = Shoot.new
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shoot }
    end
  end

  # GET /shoots/1/edit
  def edit
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    @shoot = Shoot.find(params[:id])
  end

  # POST /shoots
  # POST /shoots.xml
  def create
    @shoot = Shoot.new(params[:shoot])
    @shoot.check_mail = false
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
      if  params[:shoot][:senior_approval] == '1'
        @shoot.approver = @valid_staff
      end
      @shoot.staff = @valid_staff
    end
    if params[:story]
      if params[:story][:name] != nil and params[:story][:name].strip != ''
        story = Story.find_by_name(params[:story][:name].strip)
        if story

          @shoot.story_id = story.id
        end
      end
    end
    respond_to do |format|
      if @shoot.save
        format.html { redirect_to(@shoot, :notice => 'Shoot was successfully created.') }
        format.xml  { render :xml => @shoot, :status => :created, :location => @shoot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shoot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shoots/1
  # PUT /shoots/1.xml
  def update
    @shoot = Shoot.find(params[:id])
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
      if params[:shoot][:senior_approval] == '1'
        @shoot.approver = @valid_staff
      end
      @shoot.staff = @valid_staff
    end
    params[:shoot][:check_mail] = false
    if params[:story]
      if params[:story][:name] != nil and params[:story][:name].strip != ''
        story = Story.find_by_name(params[:story][:name].strip)
        if story

          @shoot.story_id = story.id
        end
      else
        @shoot.story_id = nil
      end
    end
    respond_to do |format|
      if @shoot.update_attributes(params[:shoot])
        format.html { redirect_to(@shoot, :notice => 'Shoot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shoot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shoots/1
  # DELETE /shoots/1.xml
  def destroy
    @shoot = Shoot.find(params[:id])
    @shoot.destroy

    respond_to do |format|
      format.html { redirect_to(shoots_url) }
      format.xml  { head :ok }
    end
  end
  def permission
    if session[:userid] == nil or session[:userid] == ''

      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
    logger.info session[:userid]
    if session[:userid] != nil and Staff.find_by_userid(session[:userid]).is_senior_producer == nil and Staff.find_by_userid(session[:userid]).is_assignment_editor == nil and Staff.find_by_userid(session[:userid]).is_producer == nil
      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
  end
  def from_story_show


    if session[:story_id] == nil and session[:story_id] == ''

      flash[:error] = "You don't have access to this section."
      redirect_to :controller => 'stories' ,:action => 'index'
    end
  end
end

app/helpers/shoots_helper.rb
module ShootsHelper
end

app/views/shoots/_form.html.erb
<%= form_for(@shoot) do |f| %>
  <% if @shoot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoot.errors.count, "error") %> prohibited this shoot from being saved:</h2>

      <ul>
        <% @shoot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :story_id %><br />
   <%= text_field_with_auto_complete :story, :name ,:value => @shoot ? (@shoot.story  ? @shoot.story.name : '') : (params[:story] ? params[:story][:name] : (Story.find_by_id(session[:story_id]) ? Story.find_by_id(session[:story_id]).name : '')) %>
       </div>
  <div class="field">
    <%= f.label :crew_requirements %><br />
    <%= f.text_area :crew_requirements, :class => "mceEditor"  %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :class => "mceEditor"  %>
  </div>
  <% if @valid_staff %>
    <% if @valid_staff.is_senior_producer == true %>
      <div class="field">
        <%= f.label :senior_approval %><br />
        <%= f.check_box :senior_approval %>
      </div>
    <% end %>
  <% end %>
  <% if @valid_staff %>
    <% if @valid_staff.is_assignment_editor == true %>
      <div class="field">
        <%= f.label :assigned %><br />
        <%= f.check_box :assigned %>
      </div>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.label :cameraperson %><br />

    <%= f.select(:cameraperson_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] }) %>

  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes ,:class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :preshow_tease %><br />
    <%= f.text_area :preshow_tease, :class => "mceEditor"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoots/_search_results.html.erb
<div id="results">
  <table>
    <tr>
      <%= sortable_table_header :name => "Date",   :sort => "date" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Name",   :sort => "name" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Crew requirements",   :sort => "crew_requirements" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Location",   :sort => "location" ,:class => 'pagination ajax' %>
      <th>Camera Person</th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true %>
          <th>Senior approval</th>
        <% end %>
      <% end %>
      <% if @valid_staff %>
        <% if @valid_staff.is_assignment_editor  == true %>
          <th>Assigned</th>
        <% end %>
      <% end %>
      <th>Notes</th>
      <th>Preshow tease</th>
      <th></th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>

      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_producer == true or @valid_staff.userid == 'admin' %>
          <th></th>
        <% end %>
      <% end %>
    </tr>

    <% @shoots.each do |shoot| %>
      <tr>
        <td><%= shoot.date %></td>
        <td><%= html_escape(shoot.name) %></td>
        <td><%= raw shoot.crew_requirements %></td>
        <td><%= raw shoot.location %></td>
        <td> <%= shoot.cameraperson ? html_escape(shoot.cameraperson.first_name + ' ' + shoot.cameraperson.last_name) : "" %> </td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true %>
            <td><%= shoot.senior_approval %></td>
          <% end %>
        <% end %>
        <% if @valid_staff %>
          <% if @valid_staff.is_assignment_editor  == true %>
            <td><%= shoot.assigned %></td>
          <% end %>
        <% end %>
        <td><%= raw shoot.notes %></td>
        <td><%= raw shoot.preshow_tease %></td>
        <td><%= link_to 'Show', shoot %></td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_shoot_path(shoot) %></td>
          <% end %>
        <% end %>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_producer == true or @valid_staff.userid == 'admin' %>
            <td><%= link_to 'Destroy', shoot, :confirm => 'Are you sure?', :method => :delete %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= will_paginate  @shoots, :class => 'pagination ajax' %>
</div>

app/views/shoots/_story.html.erb
<ul>
<% for story in @stories do %>
<li>
<div><%=h story.name %></div>
</li>
<% end %>
</ul>

app/views/shoots/edit.html.erb
<h1>Editing shoot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoot %> |
<%= link_to 'Back', shoots_path %>

app/views/shoots/index.html.erb
<%= javascript_include_tag "scriptaculous/prototype" %>

<%= javascript_include_tag "scriptaculous/scriptaculous" %>
<%= javascript_include_tag "scriptaculous/effects" %>

<%= javascript_include_tag "scriptaculous/controls" %>
<h1>Listing shoots</h1>
<%= form_for :shoot, :remote => true, :html => { :method => :get} do |f| %>
  <table>
    <tr>
      <td>
        <%= f.label :name  %>
      </td><td>
        <%= f.text_field :name, :value => params[:shoot] ? params[:shoot][:name] : '' %>
      </td><td>
        <%= f.label :crew_requirements  %>
      </td><td>
        <%= f.text_field :crew_requirements, :value => params[:shoot] ? params[:shoot][:crew_requirements] : '' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :location  %>
      </td><td>
        <%= f.text_field :location, :value => params[:shoot] ? params[:shoot][:location] : '' %>
      </td><td>
        <%= f.label :cameraperson %>
      </td><td>
        <%= f.select(:cameraperson_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] },  :selected  => params[:shoot] ? params[:shoot][:cameraperson_id] : '', :include_blank => true) %>
      </td>
    </tr>
        <tr>
      <td>
        <%= f.label :story  %>
      </td><td>
       
   <%= text_field_with_auto_complete :story, :name ,:value => params[:story] ? params[:story][:name] : (Story.find_by_id(session[:story_id]) ? Story.find_by_id(session[:story_id]).name : '') %>

      </td><td>

      </td><td>

      </td>
    </tr>
  </table>
  <br />
  <%= submit_tag("Search") %>
  <%= render "search_results" %>
  Display <%= f.select(:record_number, [[10,10], [20, 20], [50, 50], [100, 100]] , :selected => params[:shoot] ? params[:shoot][:record_number] : 10) %> records

  <br/>
  <%= link_to 'New Shoot', new_shoot_path %>
  <%= link_to 'Back', stories_path(:story =>{:approved => 1}) %>


<% end %>

app/views/shoots/new.html.erb
<h1>New shoot</h1>

<%= render 'form' %>

<%= link_to 'Back', shoots_path %>

app/views/shoots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @shoot.date %>
</p>
<p>
  <b>Name:</b>
  <%= @shoot.name %>
</p>
<p>
  <b>Crew requirements:</b>
  <%= raw @shoot.crew_requirements %>
</p>

<p>
  <b>Location:</b>
  <%= raw @shoot.location %>
</p>
<p>
  <b>Cameraperson:</b>
  <%= @shoot.cameraperson ? html_escape(@shoot.cameraperson.first_name + ' ' + @shoot.cameraperson.last_name) : "" %>
</p>
<% if @valid_staff %>
  <% if @valid_staff.is_senior_producer == true %>
    <p>
      <b>Senior approval:</b>
      <%= @shoot.senior_approval %>
    </p>
  <% end %>
<% end %>
<% if @valid_staff %>
  <% if @valid_staff.is_assignment_editor  == true %>
    <p>
      <b>Assigned:</b>
      <%= @shoot.assigned %>
    </p>
  <% end %>
<% end %>
<p>
  <b>Notes:</b>
  <%= raw @shoot.notes %>
</p>

<p>
  <b>Preshow tease:</b>
  <%= raw @shoot.preshow_tease %>
</p>

<% if @valid_staff %>
  <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
    <%= link_to 'Edit', edit_shoot_path(@shoot) %> |
  <% end %>
<% end %>
<%= link_to 'Back', url_for(:back) %>