config/routes.rb
StorySystem::Application.routes.draw do

  resources :webextras

  resources :airdates

  resources :shoots

  get "staffs/login"
  get "staffs/logout"
  get "staffs/forgot"
  get "home/index"
  get "characters/tag_list"
  get "stories/clone"
  get "stories/tag_list"
  get "staffs/contact_us"
  get "staffs/contact_staff"
  get "home/sign_in_google"
  get "home/complete_sign_in_google"
  resources :staffs
  resources :stories
  resources :characters
  resources :shoots do
  get :autocomplete_story_name, :on => :collection
end

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/story.rb
class Story < ActiveRecord::Base
  acts_as_taggable
  validates :name ,:outline ,:graphics_collateral ,:presence => true
  validates_uniqueness_of :name
  validates_length_of :name, :script, :maximum => 255
  belongs_to :producer ,:class_name => "Staff"
  belongs_to :correspondent ,:class_name => "Staff"
  belongs_to :editor ,:class_name => "Staff"
  belongs_to :staff
  has_many :airdates
  has_many :webextras
  has_many :shoots
  has_many :characters
  def Story.send_pitch
    conditions = {}
    conditions[:check_mail] = false
    conditions[:approved] = false
    pitches = Story.where("check_mail = :check_mail AND approved = :approved", conditions).find(:all)
        conditions = {}
    conditions[:is_senior_producer] = true
    seniors = Staff.where("is_senior_producer = :is_senior_producer", conditions)
    subject = 'Pitch'
    pitches.each do |pitch|
      seniors.each do |senior|

        UserMailer.send_pitch( subject, pitch, Staff.find(pitch.staff_id), senior.email).deliver
        pitch.update_attribute('check_mail', true)
      end
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.xml
  uses_tiny_mce :options => {
    :theme => 'advanced',
    :theme_advanced_resizing => true,
    :theme_advanced_buttons2 => "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    :theme_advanced_resize_horizontal => false,
    :plugins => %w{ table fullscreen }
  }
  sortable_attributes :name , :deadline
  before_filter :permission , :only => [:edit , :destroy, :clone]
  def index
    if params[:story]
      if params[:story][:approved] == '1'
        session[:approved] = true
      else
        session[:approved] = false
      end
    else
      session[:approved] = false
    end
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    query_string = ""
    conditions = {}
    if params[:story]
      if params[:story][:name] != nil and params[:story][:name] != ''
        query_string = query_string + " AND UPPER(name) LIKE :name"
        conditions[:name] = "%" + params[:story][:name].strip.upcase + "%"
      end
     
      if params[:story][:producer_id] != nil and params[:story][:producer_id] != ''
        query_string = query_string + " AND producer_id = :producer_id"
        conditions[:producer_id] = params[:story][:producer_id]
      end
      if params[:story][:correspondent_id] != nil and params[:story][:correspondent_id] != ''
        query_string = query_string + " AND correspondent_id = :correspondent_id"
        conditions[:correspondent_id] = params[:story][:correspondent_id]
      end
      if params[:story][:editor_id] != nil and params[:story][:editor_id] != ''
        query_string = query_string + " AND editor_id = :editor_id"
        conditions[:editor_id] = params[:story][:editor_id]
      end
    end
    if params[:story]

      if params[:story][:approved] == '1'
        conditions[:approved] = true
      else
        conditions[:approved] = false
      end
      if params[:story][:archived] == '1'
        conditions[:archived] = true
      else
        conditions[:archived] = false
      end
    else
      conditions[:archived] = false
      conditions[:approved] = false
    end

    conditions[:today] = Date.today()
    @stories = Story.where("approved = :approved and deadline >= :today and archived = :archived" + query_string, conditions).find(:all ,:order => sort_order).paginate :page => params[:page],:per_page => params[:story] ? params[:story][:record_number] : 10

    respond_to do |format|
      format.html # index.html.erb
      format.js {
        render :update do |page|
          # 'page.replace' will replace full "results" block...works for this example
          # 'page.replace_html' will replace "results" inner html...useful elsewhere
          page.replace 'results', :partial => 'search_results'
        end
      }

    end
  end

  # GET /stories/1
  # GET /stories/1.xml
  def show
    @story = Story.find(params[:id])
    session[:story_id] = params[:id]
    @shoots = Shoot.where("story_id = :story_id" , :story_id => session[:story_id] ).find(:all ,:order => 'created_at', :limit => 20)
    @webextras = Webextra.where("story_id = :story_id" , :story_id => session[:story_id] ).find(:all ,:order => 'created_at', :limit => 20)
    @characters = Character.where("story_id = :story_id", :story_id => session[:story_id] ).find(:all ,:order => 'created_at', :limit => 20)
    @airdates = Airdate.where("story_id = :story_id", :story_id => session[:story_id] ).find(:all ,:order => 'created_at', :limit => 20)
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.xml
  def new
    if params[:story]
      if params[:story][:approved] == '1'
        session[:approved] = true
      else
        session[:approved] = false
      end
    else
      session[:approved] = false
    end
    @story = Story.new
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
  end

  # POST /stories
  # POST /stories.xml
  def create
    @story = Story.new(params[:story])
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    @story.approved = session[:approved]
    @story.check_mail = false
    @story.staff_id = @valid_staff.id
    respond_to do |format|
      if @story.save
        if session[:approved]
          format.html { redirect_to(@story, :notice => 'Story was successfully created.') }
        else
          format.html { redirect_to(@story, :notice => 'Pitch was successfully created.') }
        end
        format.xml  { render :xml => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    @story = Story.find(params[:id])
    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end
    params[:story][:check_mail] = false
    @story.staff_id = @valid_staff.id
    respond_to do |format|
      if @story.update_attributes(params[:story])
        if session[:approved]
          format.html { redirect_to(@story, :notice => 'Story was successfully updated.') }
        else
          format.html { redirect_to(@story, :notice => 'Pitch was successfully updated.') }
        end
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to(stories_url) }
      format.xml  { head :ok }
    end
  end
  def permission
    if session[:userid] == nil or session[:userid] == ''

      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
    logger.info session[:userid]
    if session[:userid] != nil and Staff.find_by_userid(session[:userid]).is_senior_producer == nil and Staff.find_by_userid(session[:userid]).is_assignment_editor == nil and Staff.find_by_userid(session[:userid]).is_producer == nil
      flash[:notice] = "You don't have access to this section."
      redirect_to '/'
    end
  end
  def tag_list

    if session[:userid] != nil and session[:userid] != ''
      @valid_staff = Staff.find(:first, :conditions => ["userid = ? ", session[:userid]])
    end

    conditions = {}

    conditions[:approved] = true

    conditions[:today] = Date.today()
    @stories = Story.where("approved = :approved and deadline >= :today" , conditions).find(:all ,:order => sort_order).paginate :page => params[:page],:per_page => params[:story] ? params[:story][:record_number] : 10
    if params[:story]
      if params[:story][:tag_list] != nil and params[:story][:tag_list] != ''

        tag_list = params[:story][:tag_list].split(',')
        @stories = Story.where("approved = :approved and deadline >= :today" , conditions).tagged_with(tag_list,  :any => true).find(:all ,:order => sort_order).paginate :page => params[:page],:per_page => params[:story] ? params[:story][:record_number] : 10
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js {
        render :update do |page|
          # 'page.replace' will replace full "results" block...works for this example
          # 'page.replace_html' will replace "results" inner html...useful elsewhere
          page.replace 'results', :partial => 'search_results'
        end
      }

    end
  end
    def clone
    @story = Story.find(params[:id])
    @clone = Story.new(@story.attributes)
    @clone.save

    respond_to do |format|
      format.html { redirect_to(stories_path(:story =>{:approved => 1})) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_documents.html.erb
<div id="documents" class="popup" style="display:none">

  <h2>Your Google Documents</h2>
  <% if  session[:documents] %>
    <% session[:documents].each do |document| %>
  <p><%= link_to  document[:title], "javascript:void(0)", :onclick => "setScript('" + document[:url] + "' );" %>  </p>
    <% end %>
  <% end %>

</div>
  <script>
function setScript(url) {
  $("story_script").setValue(url);
}
  </script>
<%= javascript_tag "new Popup('documents','documents_link')" %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% if session[:approved] == false %>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
<% end %>
  <div class="field">
    <%= f.label :archived %><br />
    <%= f.check_box :archived %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label "Fork Id" %><br />
    <%= f.text_field :fork_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :outline %> (MUST INCLUDE STORY LINKS)<br />
    <%= f.text_area :outline , :class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :graphics_collateral %><br />
    <%= f.text_area :graphics_collateral, :class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :script %><br />
    <%= f.text_field :script %>
   <span id="documents_link" class="popup_link">Lookup</span>
<%= render :partial =>  "documents" %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :producer %><br />

    <%= f.select(:producer_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] }) %>

  </div>
  <div class="field">
    <%= f.label :correspondent %><br />

    <%= f.select(:correspondent_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] }) %>

  </div>
  <div class="field">
    <%= f.label :editor %><br />

    <%= f.select(:editor_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] }) %>

  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/stories/_search_results.html.erb
<div id="results">
  <table>
    <tr>
      <%= sortable_table_header :name => "Deadline",   :sort => "deadline" ,:class => 'pagination ajax' %>
      <%= sortable_table_header :name => "Name",   :sort => "name" ,:class => 'pagination ajax' %>
      <th>Producer</th>
      <th>Correspondent</th>
      <th>Editor</th>
      <th></th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>
      <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
        <th></th>
      <% end %>
    </tr>

    <% @stories.each do |story| %>
      <%  if story.archived == true %>

        <tr bgcolor="yellow">
        <% else %>
        <tr>
        <% end %>
        <td><%= html_escape(story.deadline) %></td>
        <td><%= html_escape(story.name) %></td>
        <td><%= story.producer ? story.producer.first_name + ' ' + story.producer.last_name : ''%></td>
        <td><%= story.correspondent ? story.correspondent.first_name + ' ' + story.correspondent.last_name : '' %></td>
        <td><%= story.editor ? story.editor.first_name + ' ' + story.editor.last_name : '' %></td>
        <td><%= link_to 'Show', story %> </td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_story_path(story) %></td>
                    <td><%= link_to 'Clone', :id => story.id , :action => 'clone' ,:controller => 'stories' %></td>
          <% end %>
        <% end %>
        <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
          <td><%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %></td>

  <% end %>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @stories, :class => 'pagination ajax' %>
</div>

app/views/stories/edit.html.erb
<% if session[:approved] == true %>
<h1>Editing story</h1>
<% else %>
<h1>Editing pitch</h1>
<% end %>
<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<% if params[:story] and params[:story][:approved] == '1' %>
  <h1>Listing Stories</h1>
<% else %>
  <h1>Listing Pitches</h1>
<% end %>
<%= form_for :story, :remote => true, :html => { :method => :get} do |f| %>
  <%= f.hidden_field :approved , :value =>params[:story] ? params[:story][:approved] : '0'  %>
  <table>
    <tr>
      <td>
        <%= f.label :name %>
      </td>
      <td>
        <%= f.text_field :name, :value => params[:story] ? params[:story][:name] : '' %>
      </td>
    </tr>
  </table>
  <%= f.label :producer %>
  <%= f.select(:producer_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] },  :selected  => params[:story] ? params[:story][:producer_id] : '', :include_blank => true) %>
  <%= f.label :correspondent %>
  <%= f.select(:correspondent_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] },  :selected  => params[:story] ? params[:story][:correspondent_id] : '', :include_blank => true) %>
  <%= f.label :editor %>
  <%= f.select(:editor_id, Staff.find(:all, :order => 'first_name asc, last_name asc').collect {|c| [c.first_name + ' ' + c.last_name, c.id ] },  :selected  => params[:story] ? params[:story][:editor_id] : '', :include_blank => true) %>
  <%= f.label "Show Archived" %>
  <%= f.check_box :archived, :value => params[:story] ? params[:story][:archived] : false %>
  <br />
  <%= submit_tag("Search") %>
  <%= render "search_results" %>
  Display <%= f.select(:record_number, [[10,10], [20, 20], [50, 50], [100, 100]] , :selected => params[:story] ? params[:story][:record_number] : 10) %> records

  <br/>
  <% if params[:story] and params[:story][:approved] == '1' %>
    <%= link_to 'New Story', new_story_path(:story =>{:approved => 1}) %>
    <%= link_to 'Tags', :controller => "stories", :action => "tag_list" %>

  <% else %>
    <%= link_to 'New Pitch', new_story_path %>

  <% end %>
<% end %>

app/views/stories/new.html.erb
<% if session[:approved] == true %>
<h1>New story</h1>
<% else %>
<h1>New pitch</h1>
<% end %>
<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<% if @story.approved == true %>
  <p>
    <%= link_to 'Airdates List', airdates_path %> |
    <%= link_to 'Shoots Search', shoots_path %> |
    <%= link_to 'Characters Search', characters_path %>
    <%= link_to 'Webextras Search', webextras_path %>
  </p>
<% end %>
<p>
  <b>Deadline:</b>
  <%= html_escape(@story.deadline) %>
</p>

<p>
  <b>Name:</b>
  <%= html_escape(@story.name) %>
</p>
<p>
  <b>Fork Id:</b>
  <%= html_escape(@story.fork_id) %>
</p>
<p>
  <b>Video:</b>
  <%= html_escape(@story.video) %>
</p>

<p>
  <b>Outline:</b>
  <%= raw  @story.outline %>
</p>

<p>
  <b>Graphics collateral:</b>
  <%= raw @story.graphics_collateral %>
</p>

<p>
  <b>Script:</b>
  <a href="<%= html_escape(@story.script)%>" >
    <%= html_escape(@story.script)%>
  </a>
</p>
<% unless @story.tag_list.empty? %>
	<p class="tags">
  	<b>Tags:</b>
  	<%= @story.tag_list %>
	</p>
<% end %>
<p>
  <b>Approved:</b>
  <%= @story.approved %>
</p>
<p>
  <b>Producer:</b>
  <%= @story.producer ? @story.producer.first_name + ' ' + @story.producer.last_name : '' %>
</p>
<p>
  <b>Correspondent:</b>
  <%=  @story.correspondent ? @story.correspondent.first_name + ' ' + @story.correspondent.last_name : ''%>
</p>
<p>
  <b>Editor:</b>
  <%=  @story.editor ? @story.editor.first_name + ' ' + @story.editor.last_name : '' %>
</p>
<% if @story.approved == true %>

<% end %>
<% if @valid_staff %>
  <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
    <%= link_to 'Edit', edit_story_path(@story) %> |
  <% end %>
<% end %>
<%= link_to 'Back', stories_path(:story =>{:approved => @story.approved ? 1 : 0}) %>
<% if @shoots.length != 0 %>
  <h1>Listing shoots</h1>
  <table>
    <tr>

      <th>Date</th>
      <th>Crew requirements</th>
      <th>Location</th>
      <th>Camera Person</th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true %>
          <th>Senior approval</th>
        <% end %>
      <% end %>
      <% if @valid_staff %>
        <% if @valid_staff.is_assignment_editor  == true %>
          <th>Assigned</th>
        <% end %>
      <% end %>
      <th>Notes</th>
      <th>Preshow tease</th>
      <th></th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_producer == true or @valid_staff.userid == 'admin' %>
          <th></th>
        <% end %>
      <% end %>
    </tr>

    <% @shoots.each do |shoot| %>
      <tr>
        <td><%= shoot.date %></td>
        <td><%= raw shoot.crew_requirements %></td>
        <td><%= raw shoot.location %></td>
        <td> <%= shoot.cameraperson ? shoot.cameraperson.userid : "" %> </td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true %>
            <td><%= shoot.senior_approval %></td>
          <% end %>
        <% end %>
        <% if @valid_staff %>
          <% if @valid_staff.is_assignment_editor  == true %>
            <td><%= shoot.assigned %></td>
          <% end %>
        <% end %>
        <td><%= raw shoot.notes %></td>
        <td><%= raw shoot.preshow_tease %></td>
        <td><%= link_to 'Show', shoot %></td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_shoot_path(shoot) %></td>
          <% end %>
        <% end %>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_producer == true or @valid_staff.userid == 'admin' %>
            <td><%= link_to 'Destroy', shoot, :confirm => 'Are you sure?', :method => :delete %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

<% end %>
<%= link_to 'New Shoot', new_shoot_path %>
<% if  @characters.length != 0 %>
  <h1>Listing characters</h1>
  <table>
    <tr>
           <th>Avatar</th>
      <th>Salutation</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>

      <th>Phone 1</th>
      <th>Phone 2</th>
      <th>Phone 3</th>
      <th>Email 1</th>
      <th>Email 2</th>

      <th>Representative</th>
      <th>Rep address</th>
      <th></th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>
      <% if session[:userid] != nil or Staff.find_by_userid(session[:userid]).userid == 'admin' %>
        <th></th>
      <% end %>
    </tr>

    <% @characters.each do |character| %>
      <tr>
               <td>  <%= image_tag character ? (character.avatar ? character.avatar : 'logo.jpg')  : 'logo.jpg', :size => "60x60" %></td>
        <td><%= html_escape(character.salutation) %></td>
        <td><%= html_escape(character.first_name) %></td>
        <td><%= html_escape(character.last_name) %></td>
        <td><%= html_escape(character.address) %></td>
        <td><%= html_escape(character.city) %></td>
        <td><%= html_escape(character.state) %></td>
        <td><%= html_escape(character.zip) %></td>
        <td><%= html_escape(character.phone_1) %></td>
        <td><%= html_escape(character.phone_2) %></td>
        <td><%= html_escape(character.phone_3) %></td>
        <td><%= html_escape(character.email_1) %></td>
        <td><%= html_escape(character.email_2) %></td>
        <td><%= html_escape(character.representative) %></td>
        <td><%= html_escape(character.rep_address) %></td>
        <td><%= link_to 'Show', character %></td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_character_path(character) %></td>
          <% end %>
        <% end %>
        <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
          <td><%= link_to 'Destroy', character, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

<% end %>
<%= link_to 'New Character', new_character_path %>
<% if @webextras.length != 0 %>
  <h1>Listing webextras</h1>
  <table>
    <tr>

      <th>Title </th>
      <th>Summary</th>
      <th> </th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>
      <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
        <th></th>
      <% end %>

    </tr>

    <% @webextras.each do |webextra| %>
      <tr>
        <td><%= html_escape(webextra.title) %></td>
        <td><%= raw webextra.summary %></td>
        <td><%= link_to 'Show', webextra %></td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_webextra_path(webextra) %></td>
          <% end %>
        <% end %>
        <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
          <td><%= link_to 'Destroy', webextra, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>
<%= link_to 'New Webextra', new_webextra_path %>
<% if  @airdates.length != 0 %>
  <h1>Listing airdates</h1>

  <table>
    <tr>
      <th>Airdate</th>
      <th></th>
      <% if @valid_staff %>
        <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
          <th></th>
        <% end %>
      <% end %>
      <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
        <th></th>
      <% end %>
    </tr>

    <% @airdates.each do |airdate| %>
      <tr>
        <td><%= airdate.airdate %></td>
        <td><%= link_to 'Show', airdate %></td>
        <% if @valid_staff %>
          <% if @valid_staff.is_senior_producer == true or @valid_staff.is_assignment_editor  == true or @valid_staff.is_producer == true %>
            <td><%= link_to 'Edit', edit_airdate_path(airdate) %></td>
          <% end %>
        <% end %>
        <% if session[:userid] != nil and Staff.find_by_userid(session[:userid]).userid == 'admin' %>
          <td><%= link_to 'Destroy', airdate, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
<% end %>
    </table>
  <% end %>
  <%= link_to 'New Airdate', new_airdate_path %>

app/views/stories/tag_list.html.erb
  <h1>Tags</h1>

<%= form_for :story, :remote => true, :html => { :method => :get} do |f| %>
  <%= f.hidden_field :approved , :value =>params[:story] ? params[:story][:approved] : '0'  %>
  <table>
    <tr>
      <td>
           <%= f.label "Type to find comma-separated tags:" %>
      </td>
      <td>
        <%= f.text_field :tag_list, :value => params[:story] ? params[:story][:tag_list] : '' %>
      </td>
    </tr>
  </table>
  <%= submit_tag("Search") %>
  <%= render "search_results" %>
  Display <%= f.select(:record_number, [[10,10], [20, 20], [50, 50], [100, 100]] , :selected => params[:story] ? params[:story][:record_number] : 10) %> records

  <br/>
  <% if params[:story] and params[:story][:approved] == '1' %>
  <%= link_to 'New Story', new_story_path(:story =>{:approved => 1}) %>
  <% else %>
    <%= link_to 'New Pitch', new_story_path %>
  <% end %>
<% end %>